### ISSUE TITLE
Faulty/missing link to pretrained models

### ISSUE THREAD

**Issue by Hoclor** [AAshqar/DSCLRCN-PyTorch#4]
Hi there!

I'm trying to run your implementation of DSCLRCN, but the Google drive link you provided (https://drive.google.com/open?id=1NiIkHm9e1fO7ilox4ZdRGkgiQZHbcr7x) for downloading the pretrained models necessary to run the implementation gives a 404 error, and thus I cannot run the model. Could you make these available again, or can I find them somewhere else?

Thanks for your help!

**Comment by plin24** [comment]
Same here, still get the 404 error. @AAshqar It would be nice to have those pre-trained models available! Thanks in advance!

**Comment by AAshqar** [comment]
Hello guys,

Thank you for your notes! I just checked the link and the models were accidentally removed. I updated the link in the readme section and now it should be working. Have fun :)
